app/views/admin.py
import os
from datetime import date
from flask import Flask, request, render_template, flash, redirect, url_for, session, send_file
from flask import Blueprint, g
from flask_mysqldb import MySQL
from passlib.hash import sha256_crypt as sha
from flask_session import Session
from tempfile import mkdtemp
from functools import wraps
import csv
from app import *

admin = Blueprint('admin', __name__, url_prefix='/admin')

p_mentors = []
p_panel = []
p_panel_id = []
p_head = []
panel_id = 0
panel_no = 0


@admin.route('/view_mentors/', methods=["GET"])
@mentor_login_required
@admin_required
def view_mentors():
    requests = query_db("select * from Requests where mentor_id = %s",(session["mentor_id"],))
    if requests is None:
        requests = []
    panel_head = query_db("select * from Panelists where mentor_id=%s AND head=1",(session["mentor_id"], ))
    is_panel_head = False
    if panel_head is None:
        is_panel_head = False
    else:
        is_panel_head = True
    mentor_limit = query_db("select group_limit from Mentors where mentor_id=%s", (session["mentor_id"], ))[0][0]
    mentor_first = query_db("select count(group_id) from Group_Mentors where mentor1_id=%s AND mentor2_id is Null;",(session["mentor_id"],))[0][0]
    mentor_second= query_db("select count(group_id) from Group_Mentors where mentor1_id=%s;",(session["mentor_id"],))[0][0] - mentor_first
    mentor_second= mentor_second + query_db("select count(group_id) from Group_Mentors where mentor2_id=%s;",(session["mentor_id"],))[0][0]
    mentor_second= mentor_second/2
    available_limit = float(mentor_limit)-(mentor_first+mentor_second)
    mentors=query_db("select mentor_id,email,name from Mentors")
    numberofgroups=[]
    for mentor in mentors:
        temp=[]
        temp.extend((mentor[0],mentor[1],mentor[2]))
        first=query_db("select count(group_id) from Group_Mentors where mentor1_id=%s AND mentor2_id is Null;",(mentor[0],))[0][0]
        second=query_db("select count(group_id) from Group_Mentors where mentor1_id=%s;",(mentor[0],))[0][0] - first
        second=second + query_db("select count(group_id) from Group_Mentors where mentor2_id=%s;",(mentor[0],))[0][0]
        second=second/2
        temp.append(first+second)
        numberofgroups.append(temp)
    return render_template("view_mentors.html", **locals(), user=session["user_id"], mentor_id=session["mentor_id"])


@admin.route('/clear_all/', methods=["GET"])
@mentor_login_required
@admin_required
def clear_all():
    execute_db("delete from Teams where 1=1")
    execute_db("delete from Students where 1=1")
    execute_db("delete from Group_Mentors where 1=1")
    execute_db("delete from Requests where 1=1")
    execute_db("delete from Panel_group where 1=1")
    execute_db("delete from Panelists where 1=1")
    execute_db("delete from Panel_Marks where 1=1")
    execute_db("delete from Panel_parameter where 1=1")
    execute_db("alter table Teams auto_increment=1")
    flash("Data cleared!", 'success')
    return redirect(url_for("mentor.mygroups"))


@admin.route('/full_marks/', methods=["GET", "POST"])
@mentor_login_required
@admin_required
def full_marks():
    requests = query_db("select * from Requests where mentor_id = %s",(session["mentor_id"],))
    if requests is None:
        requests = []
    panel_head = query_db("select * from Panelists where mentor_id=%s AND head=1",(session["mentor_id"], ))
    is_panel_head = False
    if panel_head is None:
        is_panel_head = False
    else:
        is_panel_head = True
    mentor_limit = query_db("select group_limit from Mentors where mentor_id=%s", (session["mentor_id"], ))[0][0]
    mentor_first = query_db("select count(group_id) from Group_Mentors where mentor1_id=%s AND mentor2_id is Null;",(session["mentor_id"],))[0][0]
    mentor_second= query_db("select count(group_id) from Group_Mentors where mentor1_id=%s;",(session["mentor_id"],))[0][0] - mentor_first
    mentor_second= mentor_second + query_db("select count(group_id) from Group_Mentors where mentor2_id=%s;",(session["mentor_id"],))[0][0]
    mentor_second= mentor_second/2
    available_limit = float(mentor_limit)-(mentor_first+mentor_second)
    if request.method=='GET':
        return render_template('full_marks.html', **locals(), user=session["user_id"], mentor_id=session["mentor_id"])
    else:
        full_marks = request.form['full_marks']
        eval_id = request.form['eval_id']
        if int(eval_id)<7:
            execute_db("UPDATE Evaluations SET max_marks = %s WHERE evaluation_no = %s",(full_marks, eval_id,))
        else:
            eval_id-=6
            execute_db("UPDATE panel_dates SET maxmarks = %s WHERE eval_id = %s",(full_marks, eval_id,))
        flash("Successfully updated full marks", "success")
        return redirect(url_for("mentor.mygroups"))


@admin.route('/add_admin/', methods=["GET", "POST"])
@mentor_login_required
@admin_required
def add_admin():
    requests = query_db("select * from Requests where mentor_id = %s",(session["mentor_id"],))
    if requests is None:
        requests = []
    panel_head = query_db("select * from Panelists where mentor_id=%s AND head=1",(session["mentor_id"], ))
    is_panel_head = False
    if panel_head is None:
        is_panel_head = False
    else:
        is_panel_head = True
    mentor_limit = query_db("select group_limit from Mentors where mentor_id=%s", (session["mentor_id"], ))[0][0]
    mentor_first = query_db("select count(group_id) from Group_Mentors where mentor1_id=%s AND mentor2_id is Null;",(session["mentor_id"],))[0][0]
    mentor_second= query_db("select count(group_id) from Group_Mentors where mentor1_id=%s;",(session["mentor_id"],))[0][0] - mentor_first
    mentor_second= mentor_second + query_db("select count(group_id) from Group_Mentors where mentor2_id=%s;",(session["mentor_id"],))[0][0]
    mentor_second= mentor_second/2
    available_limit = float(mentor_limit)-(mentor_first+mentor_second)
    if request.method=='GET':
        return render_template('add_admin.html', **locals(), user=session["user_id"], mentor_id=session["mentor_id"])
    else:
        email = request.form['email']
        password=request.form['password']
        mentorid = query_db("select mentor_id from Mentors where email = %s",(email,))
        phash = query_db("select password from Mentors where mentor_id = %s", (mentorid, ))
        if sha.verify(password, phash[0][0]):
            if mentorid is None:
                flash("Mentor not Found", "danger")
                return redirect(url_for("admin.add_admin"))
            is_admin = query_db("select mentor_id from Heads where mentor_id=%s",(mentorid,))
            if is_admin:
                flash("Already an admin", "warning")
                return redirect(url_for("admin.add_admin"))
            else:
                execute_db("INSERT INTO Heads(mentor_id) VALUES(%s)",(mentorid[0][0], ))
                flash("Successfully added Admin", "success")
                return redirect(url_for("mentor.mygroups"))
        else:
            flash("Incorrect Password", 'danger')
            return redirect(url_for("admin.add_admin"))


@admin.route('/eval_period/', methods=["GET", "POST"])
@mentor_login_required
@admin_required
def eval_period():
    requests = query_db("select * from Requests where mentor_id = %s",(session["mentor_id"],))
    if requests is None:
        requests = []
    panel_head = query_db("select * from Panelists where mentor_id=%s AND head=1",(session["mentor_id"], ))
    is_panel_head = False
    if panel_head is None:
        is_panel_head = False
    else:
        is_panel_head = True
    mentor_limit = query_db("select group_limit from Mentors where mentor_id=%s", (session["mentor_id"], ))[0][0]
    mentor_first = query_db("select count(group_id) from Group_Mentors where mentor1_id=%s AND mentor2_id is Null;",(session["mentor_id"],))[0][0]
    mentor_second= query_db("select count(group_id) from Group_Mentors where mentor1_id=%s;",(session["mentor_id"],))[0][0] - mentor_first
    mentor_second= mentor_second + query_db("select count(group_id) from Group_Mentors where mentor2_id=%s;",(session["mentor_id"],))[0][0]
    mentor_second= mentor_second/2
    available_limit = float(mentor_limit)-(mentor_first+mentor_second)
    if request.method=='GET':
        return render_template('eval_time.html', **locals(), user=session["user_id"], mentor_id=session["mentor_id"])
    else:
        eval_id = int(request.form['eval_id'])
        start_date = request.form['start_date']
        end_date = request.form['end_date']
        if not eval_id or not start_date or not end_date:
            flash("All Fields are Compulsary", "danger")
        else:
            if query_db("SELECT * from Evaluations where evaluation_no=%s",(eval_id,)):
                execute_db("UPDATE Evaluations SET start_date=%s, end_date=%s where evaluation_no=%s", (start_date, end_date, eval_id, ))
            else:
                execute_db("INSERT INTO Evaluations(start_date, end_date, evaluation_no, max_marks) values(%s,%s,%s, 5)", (start_date, end_date, eval_id, ))
        flash("Evaluation Period Updated Successfully", "success")
        return redirect(url_for("admin.eval_period"))

@admin.route("/create_panel/", methods=["GET", "POST"])
@mentor_login_required
@admin_required
def panel():
    global p_mentors, p_panel, panel_no, p_head, p_panel_id, panel_id, panels_no
    p_panel_id = []
    follow_up = False
    requests = query_db("select * from Requests where mentor_id = %s",(session["mentor_id"],))
    if requests is None:
        requests = []
    panel_head = query_db("select * from Panelists where mentor_id=%s AND head=1",(session["mentor_id"], ))
    is_panel_head = False
    if panel_head is None:
        is_panel_head = False
    else:
        is_panel_head = True
    mentor_limit = query_db("select group_limit from Mentors where mentor_id=%s", (session["mentor_id"], ))[0][0]

app/views/auth.py
import random
import string
from flask import Flask, request, render_template, flash, redirect, url_for, session, Blueprint
from flask_mysqldb import MySQL
from passlib.hash import sha256_crypt as sha
from flask_session import Session
from flask_mail import Mail, Message
from app import *
auth = Blueprint('auth', __name__, url_prefix='/mentor')

@auth.route('/login', methods=['POST','GET'])
def login():
    if request.method== 'GET':
        return render_template('login.html',SITE_KEY=SITE_KEY)
    else:
        email=request.form['email']
        password=request.form['password']
        phash = query_db("select password from Mentors where email = %s", (email, ))
        mentorid = query_db("select mentor_id from Mentors where email = %s", (email, ))
        # captcha_response = request.form['g-recaptcha-response']

        # if is_human(captcha_response):
        if True:
            if phash is None:
                flash("User does not exist","danger")
                return render_template("login.html",SITE_KEY=SITE_KEY)

            if sha.verify(password, phash[0][0]):
                session["user_id"] = email
                session["mentor_id"] = mentorid[0][0]
                if query_db("select mentor_id from Heads where mentor_id=%s", (mentorid[0][0], )):
                    session["admin"] = True
                else:
                    session["admin"] = False
                flash("Login Successful", "success")
                return redirect(url_for('mentor.mygroups'))
            else:
                flash("Incorrect Password","danger")
                return redirect(url_for('auth.login'))
        else:
            flash("Sorry. Bots not allowed!","danger")
            return redirect(url_for('auth.login'))

@auth.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for("auth.login"))

# @auth.route('/signup',methods=['POST','GET'])
# def signup():
#     if request.method== 'GET':
#         return render_template('signup.html',SITE_KEY=SITE_KEY)
#     else:
#         name=request.form['name']
#         email=request.form['email']
#         password=request.form['password']
#         confpassword=request.form['confpassword']
#         # captcha_response = request.form['g-recaptcha-response']

#         # if is_human(captcha_response):
#         if True:
#             if password!=confpassword:
#                 flash("Passwords don't match","danger")
#                 return render_template("signup.html",SITE_KEY=SITE_KEY)

#             if query_db("select email from Mentors where email = %s", (email,)) is not None:
#                 flash("User already taken","danger")
#                 return render_template("signup.html",SITE_KEY=SITE_KEY)

#             password=sha.encrypt(password)
#             execute_db('insert into Mentors(name,email,password) values(%s,%s,%s)',(
#                 name,
#                 email,
#                 password,
#                 ))
#             return redirect(url_for("auth.login"))
#         else:
#             flash("Sorry. Bots not allowed!","danger")
#             return redirect(url_for('auth.login'))

@auth.route('/reset_pass/', methods=['POST','GET'])
def reset_link():
    if request.method=="GET":
        return render_template("reset_link.html", SITE_KEY=SITE_KEY)
    else:
        email_id = request.form["email"]
        # captcha_response = request.form['g-recaptcha-response']
        
        # if is_human(captcha_response):
        if True:
            records = query_db("SELECT * FROM Mentors where email=%s", (email_id, ))
            if records is None:
                flash("Incorrect Email ID", "danger")
            else:
                link = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(20))
                execute_db("UPDATE Mentors set reset_link=%s where email=%s", (link, email_id, ))

                link = "http://172.31.3.184/reset/"+link

                ## Composing Mail
                title="Capstone Project Mentor Password Reset Request"
                sender="no-reply@thapar.edu"
                recipients = [email_id]
                message_html = "Your request has been received. Use this link to reset your password: <br><br> <a href=\""+link+"\">"+link+"</a>"
                send_mail(title,sender,recipients,message_html) # Sending Mail
                ## End of Mail
                flash("Reset Link Sent", "success")
            return redirect(url_for('auth.reset_link'))
        else:
            flash("Sorry. Bots not allowed!","danger")
            return render_template("reset_link.html",SITE_KEY=SITE_KEY)
        

@app.route('/reset/<string:reset_link>/', methods=["GET", "POST"])
def reset_password(reset_link):
    if request.method=="GET":
        records = query_db("SELECT * FROM Mentors where reset_link=%s", (reset_link, ))
        verified = False
        if records is not None:
            verified = True
        return render_template("reset_password.html", **locals(), SITE_KEY=SITE_KEY)
    else:
        records = query_db("SELECT * FROM Mentors where reset_link=%s", (reset_link, ))[0][2]
        password = request.form["password"]
        confpassword = request.form["confpassword"]
        # captcha_response = request.form['g-recaptcha-response']
        # if is_human(captcha_response):
        if True:
            if password!=confpassword:
                flash("Passwords don't match","danger")
                return redirect(url_for('auth.login'))
                # return render_template("reset_password.html",SITE_KEY=SITE_KEY)    
            else:
                password=sha.encrypt(password)
                execute_db('UPDATE Mentors SET password=%s, reset_link=NULL where email=%s',(
                    password,
                    records,
                ))
                flash("Password Reset Successful", "success")
        else:
            flash("Sorry. Bots not allowed!","danger")
        return redirect(url_for('auth.login'))

app/templates/add_announcements.html
{% extends 'dashboard.html' %}

{% block main %}
  <div class="col-lg-8 col-md-7">
    <div class="card">
      <div class="header">
        <h4 class="title">Add Announcement</h4>
      </div>
      <div class="content">
        <form action="{{ url_for('admin.add_announcement') }}" method="post">
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Title</label>
                  <input class="form-control border-input" name="title" placeholder="Title" type="text">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Description</label>
                <textarea rows="8" class="form-control border-input" placeholder="Here can be your Description" name="desc"></textarea>
              </div>
            </div>
          </div>

          <div class="text-center">
            <button type="submit" class="btn btn-info btn-fill btn-wd">Submit</button>
          </div>
          <div class="clearfix"></div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

app/templates/announcements.html
{% extends 'dashboard_teams.html' %}

{% block main %}
  <div class="col-lg-8 col-md-7">
    <div class="card">
      <div class="header">
        <h4 class="title">Announcements</h4>
      </div>
      <div class="content">
        <ol>
        {% for record in query %}
            <li>
                <b style="font-size: 1.6em"> {{ record[1] }} </b> &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                <i class="ti-calendar"></i> Dated:- {{ record[3] }}
                <p> {{ record[2] }}</p>
            </li> </br>
        {% endfor %}
        </ol>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/change.html
{% extends 'dashboard.html' %}

{% block main %}
  <div class="col-lg-8 col-md-7">
    <div class="card">
      <div class="header">
        <h4 class="title">Change Password</h4>
      </div>
      <div class="content">
        <form action="{{ url_for('mentor.change') }}" method="post">
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Old Password</label>
                  <input class="form-control border-input" name="oldpassword" placeholder="Old Password" type="password">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>New Password</label>
                  <input class="form-control border-input" name="newpassword" placeholder="New Password" type="password">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Confirm New Password</label>
                  <input class="form-control border-input" name="confpassword" placeholder="Confirm New Password" value="" type="password">
              </div>
            </div>
          </div>

          <div class="text-center">
            <button type="submit" class="btn btn-info btn-fill btn-wd">Submit</button>
          </div>
          <div class="clearfix"></div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

app/templates/dashboard.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" sizes="96x96" href="/images/icons/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Dashboard</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="/css/bootstrap.min.css" rel="stylesheet" />
	<link href="/css/bootstrap-select.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="/css/animate.min.css" rel="stylesheet"/>

    <!--  Capstone core CSS    -->
    <link href="/css/capstone.css" rel="stylesheet"/>

    <!--  Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='/css/Muli-font.css' rel='stylesheet' type='text/css'>
    <link href="/css/themify-icons.css" rel="stylesheet">
  <!-- CSS Just for demo purpose, don't include it in your project -->
</head>

{% block modal %}
{% endblock %}

<div class="modal fade" id="ModalCenter" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="ModalLongTitle">Confirmation</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-body">
          <h4 class="text-center"> Are you sure? </h4>
        </div>
        <div class="modal-footer">
          <a type="button" class="btn btn-info" href="{{ url_for('admin.panel') }}">OK</a>
          <a type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
        </div>
    </div>
  </div>
</div>

<body>

<div class="wrapper">
    <div class="sidebar" data-background-color="white" data-active-color="danger">

    	<div class="sidebar-wrapper">
            <div class="logo">
            <img src="/images/logo.png">
                    <a style="font-size:1em;" class="simple-text">
                        <b>Capstone Project Portal</b>
                    </a>
            </div>

        		<ul class="nav">
                <li {% if request.path == url_for('mentor.mygroups') %}class="active"{% endif %}>
                    <a href="{{ url_for('mentor.mygroups')}}">
						<i class="ti-home"></i>
                        <p> My Groups</p>
                    </a>
                </li>

                <li {% if request.path == url_for('mentor.searchgroup') %}class="active"{% endif %}>
                    <a href="{{ url_for('mentor.searchgroup') }}">
                        <i class="ti-search"></i>
                        <p>Search Group</p>
                    </a>
                </li>

                <li {% if request.path == url_for('mentor.searchstudent') %}class="active"{% endif %}>
                    <a href="{{ url_for('mentor.searchstudent') }}">
                        <i class="ti-user"></i>
                        <p>Search Student</p>
                    </a>
                </li>

                <li {% if request.path == url_for('mentor.download') %}class="active"{% endif %}>
                    <a href="{{ url_for('mentor.download') }}">
                        <i class="ti-import"></i>
                        <p>Download Data</p>
                    </a>
                </li>

                {% if session["admin"] %}
                <li {% if request.path == url_for('admin.download_all') %}class="active"{% endif %}>
                    <a href="{{ url_for('admin.download_all') }}">
                        <i class="ti-receipt"></i>
                        <p>Generate Report</p>
                    </a>
                </li>
                {% endif %}

			    {% if is_panel_head %}
                <li {% if request.path == url_for('mentor.panel_marks') %}class="active"{% endif %}>
                    <a href="{{ url_for('mentor.panel_marks') }}">
                        <i class="ti-pencil-alt"></i>
                        <p>Panel Marks</p>
                    </a>
                </li>
				{% endif %}

            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#">
											{% if request.path == url_for('mentor.mygroups') %}
												My Groups
											{% elif request.path == url_for('mentor.searchgroup') %}
												Search Group
											{% elif request.path == url_for('mentor.searchstudent') %}
                                                Search Student
                                            {% elif request.path == url_for('mentor.change') %}
                                                Change Password
											{% else %}
												Admin Tools
											{% endif %}
										</a>
										<h6> Available Group Limit - <br>
											{% if available_limit >0 %}
												{{ available_limit }}
											{% else %}
												0
											{% endif %}
										</h6>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">

                        <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="ti-bell"></i>
                                        <p>Notifications <span class="badge badge-light">
                                        {{ requests|length }}
                                        </span></p>
                                        <b class="caret"></b>
                                    </a>
                        <ul class="dropdown-menu">


                            {% for request in requests %}
                            <li><a href="{{ url_for('mentor.show_request', lead_id=request[1])}}"><b>{{request[2]|title_split}} by {{request[7]}}'s group</b></a></li>
                            {% endfor %}


                            </ul>
                            </li>



						<li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="ti-settings"></i>
								<p>{{ user }}</p>
                            </a>
                            <ul class="dropdown-menu">
                                {% if session["admin"] %}
                                <li><a href="{{ url_for('admin.add_admin') }}">Add Admin</a></li>
                                <li><a href="{{ url_for('admin.full_marks') }}">Change Full Marks</a></li>
                                <li><a href="{{ url_for('admin.eval_period') }}">Change Evaluation Period</a></li>
                                <li><a href="{{ url_for('admin.define_params') }}">Panel Parameters</a></li>
								<li><a href="{{ url_for('admin.view_mentors') }}">View Mentors</a></li>
                                <li><a href="{{ url_for('admin.group_limit') }}">Change Mentor's Group Limit</a></li>
								<li><a href="{{ url_for('admin.add_announcement') }}">Add Announcement</a></li>
                                <li><a data-toggle="modal" data-target="#ModalCenter">Panel Formation</a></li>
                                <li><a href="{{ url_for('admin.delete_group') }}">Delete Group</a></li>
                                {% endif %}
                                <li><a href="{{ url_for('mentor.edit_group') }}">Edit Group</a></li>
																<li><a href="{{ url_for('mentor.add_mentor') }}">Add Mentor</a></li>
                                <li><a href="{{ url_for('mentor.change') }}">Change Password</a></li>
                                <li><a href="{{ url_for('auth.logout') }}">Sign Out</a></li>
                              </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>


        <div class="content">
            <div class="container-fluid">
                {% block main %}
				{% endblock %}
            </div>
        </div>
    </div>
</div>


</body>

    <!--   Core JS Files   -->
    <!-- <script src="/js/jquery-1.10.2.js" type="text/javascript"></script> -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="/js/bootstrap-select.js" type="text/javascript"></script>
    <script src="/js/picker.js" type="text/javascript"></script>
    <script src="/js/picker.date.js" type="text/javascript"></script>
    <script src="/js/picker.time.js" type="text/javascript"></script>
    <link href="/css/default.css" rel="stylesheet">
    <link href="/css/default.date.css" rel="stylesheet">
    <link href="/css/default.time.css" rel="stylesheet">

	<!--  Checkbox, Radio & Switch Plugins -->
	<script src="/js/bootstrap-checkbox-radio.js"></script>
	<script src="/assets/js/plugins/jquery.dataTables.min.js"></script>
    <!--  Notifications Plugin    -->
    <script src="/js/bootstrap-notify.js"></script>

    <!-- Capstone Core javascript and methods for Demo purpose -->
	<script src="/js/capstone.js"></script>

	<!-- Capstone DEMO methods, don't include it in your project! -->
    <script src="/js/demo.js"></script>

    <script type="text/javascript">
        {% with messages = get_flashed_messages(with_categories=true) %}
			{% if messages %}
				function flashMessages() {
					{% for category, message in messages %}
					$.notify({
						icon: "ti-bell",
						message: '{{ message }}'
					},{
						type: '{{ category }}',
						timer: 4000,
						placement: {
							from: "top",
							align: "center"
					}
					});
					{% endfor %}
				}
        		window.onload = flashMessages;
            {% endif %}
        {% endwith %}

				$(document).ready(function() {

					$('.selectpicker').selectpicker();

					$(".picker__input").click(function(){

							$("#datepicker").pickadate({
									formatSubmit: 'yyyy/mm/dd',
									hiddenName: true
							});

					});

					$(".picker__input").click(function(){

							$("#datepicker2").pickadate({
									formatSubmit: 'yyyy/mm/dd',
									hiddenName: true
							});

					});

				});
    </script>


</html>

app/templates/reset_link.html
{% extends 'index_login.html'%}
{% block content %}
<form class="login100-form" action="" method="POST" accept-charset="utf-8">
  <span class="login100-form-title p-b-59">
    Send Reset Password Link
  </span>

  <div class="wrap-input100">
    <span class="label-input100">Email</span>
    <input class="input100" type="text" name="email" placeholder="email@thapar.edu" required>
    <span class="focus-input100"></span>
  </div>

<!--<div class="g-recaptcha" data-sitekey="{{SITE_KEY}}"></div>-->

  <div class="container-login100-form-btn">
    <div class="wrap-login100-form-btn">
      <div class="login100-form-bgbtn"></div>
      <button class="login100-form-btn" type="submit">
        Send Link
      </button>
    </div>
  </div>

</form>
{% endblock %}